// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lousxuhyqvxkmyjhzqcj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvdXN4dWh5cXZ4a215amh6cWNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MTA0NjksImV4cCI6MjA1ODk4NjQ2OX0.3NOBp7NjTjZsXGImIqHu74Fa2qZt7c02NGFWP8AfSOE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);